-- this file is auto-generated by BigWigs Packager from CurseForge localizations
local L = select(2, ...).L('znCH') -- luacheck: ignore
--@localization(locale="znCH", format="lua_additive_table", handle-unlocalized="blank")@
